"""
Replay the early position-building portion of the 9d62 depth VS offline.

Current scope:
- Decode the fixed section/basis selection for a dumped draw.
- Export the raw custom `vb0` mesh.
- Export the "basis-applied before t3/t5/t6" mesh:
    position = offset + vb0.x * basis_x + vb0.y * basis_y + vb0.z * basis_z

This intentionally stops before the later t3/t5/t6 correction chain. The goal is
to answer a narrow question first: does the mesh already become wrong when 9d62
applies the section basis to our local skinned position buffer?

Usage:
    python tools/replay_9d62_depth_chain.py

Outputs:
    <FRAME_DIR>/replay_9d62_000148/
      - 000148_vb0_raw.obj
      - 000148_basis_applied.obj
      - 000148_report.json
"""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import struct
from typing import Iterable


FRAME_DIR = Path(r"E:\yh\FrameAnalysis-2026-04-26-005519")
DRAW_NAME = "000148"
OUTPUT_DIR = FRAME_DIR / "replay_9d62_000148"


@dataclass(frozen=True)
class DrawFiles:
    ib: Path
    vb0: Path
    vb1: Path
    cb1: Path
    cb2: Path
    t0: Path
    t1: Path
    t2: Path


FILES = DrawFiles(
    ib=FRAME_DIR / f"{DRAW_NAME}-ib-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    vb0=FRAME_DIR / f"{DRAW_NAME}-vb0-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    vb1=FRAME_DIR / f"{DRAW_NAME}-vb1=1236657b-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    cb1=FRAME_DIR / f"{DRAW_NAME}-vs-cb1=6e5a5274-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    cb2=FRAME_DIR / f"{DRAW_NAME}-vs-cb2=0c8934aa-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    t0=FRAME_DIR / f"{DRAW_NAME}-vs-t0=81189244-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    t1=FRAME_DIR / f"{DRAW_NAME}-vs-t1=135e128a-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
    t2=FRAME_DIR / f"{DRAW_NAME}-vs-t2=ab75cfe2-vs=9d62ac15f0b2cf93-ps=f1a15881ff8cc63c.buf",
)


def read_u16_indices(path: Path) -> list[int]:
    raw = path.read_bytes()
    if len(raw) % 2 != 0:
        raise ValueError(f"{path} size is not divisible by 2: {len(raw)}")
    return list(struct.unpack(f"<{len(raw) // 2}H", raw))


def read_float3_positions(path: Path) -> list[tuple[float, float, float]]:
    raw = path.read_bytes()
    if len(raw) % 12 != 0:
        raise ValueError(f"{path} size is not divisible by 12: {len(raw)}")
    values = struct.unpack(f"<{len(raw) // 4}f", raw)
    return [
        (values[index], values[index + 1], values[index + 2])
        for index in range(0, len(values), 3)
    ]


def read_u32_words(path: Path) -> list[int]:
    raw = path.read_bytes()
    if len(raw) % 4 != 0:
        raise ValueError(f"{path} size is not divisible by 4: {len(raw)}")
    return list(struct.unpack(f"<{len(raw) // 4}I", raw))


def read_f32_words(path: Path) -> list[float]:
    raw = path.read_bytes()
    if len(raw) % 4 != 0:
        raise ValueError(f"{path} size is not divisible by 4: {len(raw)}")
    return list(struct.unpack(f"<{len(raw) // 4}f", raw))


def as_f32(u32_value: int) -> float:
    return struct.unpack("<f", struct.pack("<I", u32_value & 0xFFFFFFFF))[0]


def grouped(words: list[int], width: int) -> list[tuple[int, ...]]:
    if len(words) % width != 0:
        raise ValueError(f"Word count {len(words)} is not divisible by {width}")
    return [tuple(words[index : index + width]) for index in range(0, len(words), width)]


def bbox(positions: Iterable[tuple[float, float, float]]) -> dict[str, list[float]]:
    points = list(positions)
    if not points:
        return {
            "min": [0.0, 0.0, 0.0],
            "max": [0.0, 0.0, 0.0],
            "mean": [0.0, 0.0, 0.0],
        }

    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    zs = [point[2] for point in points]
    count = float(len(points))
    return {
        "min": [min(xs), min(ys), min(zs)],
        "max": [max(xs), max(ys), max(zs)],
        "mean": [sum(xs) / count, sum(ys) / count, sum(zs) / count],
    }


def write_obj(path: Path, positions: list[tuple[float, float, float]], indices: list[int]):
    if len(indices) % 3 != 0:
        raise ValueError(f"Index buffer length is not divisible by 3: {len(indices)}")

    lines: list[str] = ["# Generated by replay_9d62_depth_chain.py"]
    for x, y, z in positions:
        lines.append(f"v {x:.9g} {y:.9g} {z:.9g}")

    for index in range(0, len(indices), 3):
        a = indices[index] + 1
        b = indices[index + 1] + 1
        c = indices[index + 2] + 1
        lines.append(f"f {a} {b} {c}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def decode_section_selector(vb1_words: list[int], t0_records: list[tuple[int, ...]], t1_records: list[tuple[int, ...]], cb2_words: list[int]) -> dict[str, int]:
    selector = vb1_words[0]
    packed_selector = t0_records[selector][0]
    low24 = packed_selector & 0x00FFFFFF
    shift = cb2_words[0]
    mask = cb2_words[1]
    stride = cb2_words[2]
    page = low24 >> shift
    slot = low24 & mask
    t1_index = stride * page + slot
    t1_entry = t1_records[t1_index][0]
    section_index = t1_entry & 0x000FFFFF

    return {
        "instance_selector": selector,
        "t0_packed_selector": packed_selector,
        "low24": low24,
        "shift": shift,
        "mask": mask,
        "stride": stride,
        "page": page,
        "slot": slot,
        "t1_index": t1_index,
        "t1_entry": t1_entry,
        "section_index": section_index,
    }


def decode_basis(section_index: int, t1_records: list[tuple[int, ...]], t2_records: list[tuple[int, ...]], cb1_words: list[float], selector_info: dict[str, int]) -> dict[str, object]:
    shift = selector_info["shift"]
    stride = selector_info["stride"]
    page = selector_info["page"]
    slot = selector_info["slot"]

    section_entry = t2_records[section_index * 44 + 1]

    secondary_left_index = slot + stride * page + (1 << shift)
    secondary_right_index = slot + stride * page + (2 << shift)

    left_entry = t1_records[secondary_left_index]
    right_entry = t1_records[secondary_right_index]

    r2_x, r2_y, r2_z, r2_w = left_entry
    r0_x_raw, r0_z_raw, _ = right_entry[:3]

    r3_x_u = (r2_x >> 16) & 0xFFFFFFFF
    r3_y_u = (r2_z >> 16) & 0xFFFFFFFF
    r3_z_u = (r2_w >> 16) & 0xFFFFFFFF

    r4_x_u = r2_x & 0xFFFF
    r4_y_u = r2_y & 0x7FFF
    r4_z_flag = r2_y & 0x8000

    qx = (-32768.0 + float(r4_x_u)) * 3.05185094e-05
    qy = (-32768.0 + float(r3_x_u)) * 3.05185094e-05
    qw = (-16384.0 + float(r4_y_u)) * 4.3161006e-05

    v5_x = qx + qy
    v5_y = qx - qy
    v5_z = 2.0 - (abs(v5_x) + abs(v5_y))
    inv_length = 1.0 / ((v5_x * v5_x + v5_y * v5_y + v5_z * v5_z) ** 0.5)
    v5_x *= inv_length
    v5_y *= inv_length
    v5_z *= inv_length

    inv_one_plus_z = 1.0 / (1.0 + v5_z)
    tmp_y = (-v5_x * v5_y) * inv_one_plus_z

    r7_x = 1.0 - (v5_x * v5_x) * inv_one_plus_z
    r7_y = 1.0 - (v5_y * v5_y) * inv_one_plus_z
    r7_z = tmp_y
    r7_w = -v5_x

    alt = (1.0 - qw * qw) ** 0.5
    if r4_z_flag != 0:
        left_scale = alt
        right_scale = qw
    else:
        left_scale = qw
        right_scale = alt

    r4_x = r7_x * left_scale + r7_z * right_scale
    r4_y = r7_w * left_scale + r7_y * right_scale
    r4_z = r7_z * left_scale + r7_w * right_scale

    r6_x = v5_y * r4_z - v5_z * r4_y
    r6_y = v5_z * r4_x - v5_x * r4_z
    r6_z = v5_x * r4_y - v5_y * r4_x

    scale_bits = ((r3_z_u << 23) + 0xF8800000) & 0xFFFFFFFF
    scale = as_f32(scale_bits)

    scale_x = (float(r3_x_u & 0xFFFF) - 32768.0) * scale
    scale_y = (float(r3_y_u & 0xFFFF) - 32768.0) * scale
    scale_z = (float(r3_z_u & 0xFFFF) - 32768.0) * scale

    basis_x = (r4_x * scale_x, r4_y * scale_x, r4_z * scale_x)
    basis_y = (r6_x * scale_y, r6_y * scale_y, r6_z * scale_y)
    basis_z = (v5_x * scale_z, v5_y * scale_z, v5_z * scale_z)

    cb1_84 = tuple(cb1_words[84 * 4 : 84 * 4 + 3])
    cb1_85 = tuple(cb1_words[85 * 4 : 85 * 4 + 3])

    t2_offset = tuple(as_f32(value) for value in section_entry[:3])
    t1_offset = (as_f32(r0_x_raw), as_f32(r0_z_raw), 0.0)

    offset = (
        cb1_84[0] + cb1_85[0] + t2_offset[0] + t1_offset[0],
        cb1_84[1] + cb1_85[1] + t2_offset[1] + t1_offset[1],
        cb1_84[2] + cb1_85[2] + t2_offset[2] + t1_offset[2],
    )

    section_words = list(t2_records[section_index * 44 : section_index * 44 + 44])

    return {
        "basis_x": basis_x,
        "basis_y": basis_y,
        "basis_z": basis_z,
        "offset": offset,
        "cb1_84": cb1_84,
        "cb1_85": cb1_85,
        "section_entry_1_raw": list(section_entry),
        "section_entry_1_as_float": [as_f32(value) for value in section_entry],
        "secondary_left_index": secondary_left_index,
        "secondary_right_index": secondary_right_index,
        "secondary_left_entry": list(left_entry),
        "secondary_right_entry": list(right_entry),
        "section_words_uint": [list(entry) for entry in section_words],
        "section_words_float": [[as_f32(value) for value in entry] for entry in section_words],
    }


def apply_basis(
    positions: list[tuple[float, float, float]],
    basis_x: tuple[float, float, float],
    basis_y: tuple[float, float, float],
    basis_z: tuple[float, float, float],
    offset: tuple[float, float, float],
) -> list[tuple[float, float, float]]:
    out: list[tuple[float, float, float]] = []
    for x, y, z in positions:
        out.append(
            (
                offset[0] + x * basis_x[0] + y * basis_y[0] + z * basis_z[0],
                offset[1] + x * basis_x[1] + y * basis_y[1] + z * basis_z[1],
                offset[2] + x * basis_x[2] + y * basis_y[2] + z * basis_z[2],
            )
        )
    return out


def build_report(
    *,
    raw_positions: list[tuple[float, float, float]],
    basis_positions: list[tuple[float, float, float]],
    indices: list[int],
    selector_info: dict[str, int],
    basis_info: dict[str, object],
) -> dict[str, object]:
    return {
        "frame_dir": str(FRAME_DIR),
        "draw_name": DRAW_NAME,
        "index_count": len(indices),
        "vertex_count": len(raw_positions),
        "index_min": min(indices) if indices else 0,
        "index_max": max(indices) if indices else 0,
        "index_unique": len(set(indices)),
        "raw_vb0_bbox": bbox(raw_positions),
        "basis_applied_bbox": bbox(basis_positions),
        "selector_info": selector_info,
        "basis_info": basis_info,
        "notes": [
            "This replay intentionally stops before the t3/t5/t6 correction chain.",
            "The basis-applied mesh corresponds to the position-building stage before those later corrections.",
            "If this mesh is already wildly wrong in Blender, the problem starts at section/basis interpretation.",
            "If this mesh still looks plausible, continue replaying the later correction chain next.",
        ],
    }


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    indices = read_u16_indices(FILES.ib)
    raw_positions = read_float3_positions(FILES.vb0)
    vb1_words = read_u32_words(FILES.vb1)
    cb1_words = read_f32_words(FILES.cb1)
    cb2_words = read_u32_words(FILES.cb2)
    t0_records = grouped(read_u32_words(FILES.t0), 4)
    t1_records = grouped(read_u32_words(FILES.t1), 4)
    t2_records = grouped(read_u32_words(FILES.t2), 4)

    selector_info = decode_section_selector(vb1_words, t0_records, t1_records, cb2_words)
    basis_info = decode_basis(selector_info["section_index"], t1_records, t2_records, cb1_words, selector_info)
    basis_positions = apply_basis(
        raw_positions,
        basis_x=basis_info["basis_x"],
        basis_y=basis_info["basis_y"],
        basis_z=basis_info["basis_z"],
        offset=basis_info["offset"],
    )

    raw_obj_path = OUTPUT_DIR / f"{DRAW_NAME}_vb0_raw.obj"
    basis_obj_path = OUTPUT_DIR / f"{DRAW_NAME}_basis_applied.obj"
    report_path = OUTPUT_DIR / f"{DRAW_NAME}_report.json"

    write_obj(raw_obj_path, raw_positions, indices)
    write_obj(basis_obj_path, basis_positions, indices)

    report = build_report(
        raw_positions=raw_positions,
        basis_positions=basis_positions,
        indices=indices,
        selector_info=selector_info,
        basis_info=basis_info,
    )
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Wrote: {raw_obj_path}")
    print(f"Wrote: {basis_obj_path}")
    print(f"Wrote: {report_path}")
    print(f"Section: {selector_info['section_index']}")
    print(f"basis_x: {basis_info['basis_x']}")
    print(f"basis_y: {basis_info['basis_y']}")
    print(f"basis_z: {basis_info['basis_z']}")
    print(f"offset : {basis_info['offset']}")
    print(f"raw bbox   : {bbox(raw_positions)}")
    print(f"basis bbox : {bbox(basis_positions)}")


if __name__ == "__main__":
    main()
